FROM debian:sid

WORKDIR /tmp
RUN apt-get update && \
    apt-get install -y zlib1g-dev build-essential wget qt4-default libgcrypt20-dev cmake && \
    wget  https://www.keepassx.org/releases/2.0.3/keepassx-2.0.3.tar.gz && \
    tar xzvf keepassx-2.0.3.tar.gz && \
    cd keepassx-2.0.3 && \
    cmake . && make &&  make install && \
    rm -rf /var/lib/apt/lists/* /tmp/*

ENTRYPOINT ["/usr/local/bin/keepassx"]
