FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends --fix-missing\
    libgl-dev \
    qt5dxcb-plugin \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

ADD https://download.studio3t.com/studio-3t/linux/2021.7.1/studio-3t-linux-x64.tar.gz /opt/robo3t.tar.gz
RUN cd /opt/ \
    && mkdir robo3t \
    && tar -C /opt/robo3t --strip-components 1 -xzf robo3t.tar.gz && rm robo3t.tar.gz \
    && ls /opt/robo3t

VOLUME /root/.3T
VOLUME /root/.config/3T

CMD /opt/robo3t/bin/robo3t
