# {{ ansible_managed }}
FROM debian:buster
RUN apt-get update && apt-get install -y \
	ca-certificates \
    apt-transport-https \
    curl \
    default-jdk \
    gnupg \
    wget

RUN curl -sSL https://dbeaver.io/debs/dbeaver.gpg.key | apt-key add - \
    && echo "deb https://dbeaver.io/debs/dbeaver-ce /" | tee /etc/apt/sources.list.d/dbeaver.list

RUN apt-get update && apt-get install -y \
    dbeaver-ce
