# {{ ansible_managed }}
FROM debian:buster

RUN apt-get update && apt-get install -y apt-transport-https curl sudo gnupg2
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

RUN sudo apt-get update && apt-get install -y kubectl && rm -rf /var/lib/apt/lists/*

ENTRYPOINT [ "kubectl" ]
CMD [ "--help" ]
