" {{ ansible_managed }}

call plug#begin('~/.nvim/plugged')
    Plug 'lilydjwg/colorizer'
    Plug 'altercation/vim-colors-solarized'
    Plug 'tpope/vim-fugitive'
    Plug 'pearofducks/ansible-vim'
    Plug 'nginx.vim'
    Plug 'lepture/vim-jinja'
    Plug 'vim-gitgutter'
    Plug 'Valloric/YouCompleteMe', { 'for': ['cpp', 'python'], 'do': './install.py --clang-completer' }
    Plug 'scrooloose/syntastic'
    Plug 'jiangmiao/auto-pairs'
    Plug 'junegunn/seoul256.vim'
    Plug 'terryma/vim-multiple-cursors'
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    Plug 'junegunn/fzf.vim'
    Plug 'scrooloose/nerdtree' 
    autocmd! User YouCompleteMe call youcompleteme#Enable()
call plug#end()

" terminal
" This maps Leader + e to exit terminal mode.
tnoremap <Esc> <C-\><C-n>

" Fuzzy search
nnoremap <Leader>p :FZF<cr>

" nerdtree
let g:nerdtree_tabs_open_on_gui_startup=1
let g:nerdtree_tabs_open_on_console_startup=1

autocmd! bufwritepost .nvimrc source %
autocmd vimenter * NERDTree

" global
filetype off
filetype indent on
filetype plugin on

let g:seoul256_background = 236
colo seoul256
set background=dark
syntax on

set autoindent
set background=light
set clipboard+=unnamed
set colorcolumn=79
set expandtab
set foldmethod=manual
set go+=a
set guifont=Monospace\ 6
set guioptions+=a
set hlsearch
set ls=2
set modifiable
set nocompatible
set number
set paste
set shiftwidth=4
set si
set siso=1
set sm
set softtabstop=4
set t_Co=256
set tabstop=4
set virtualedit=onemore

map <right> <esc>
map <left> <esc>
map <up> <esc>
map <down> <esc>
imap <right> <esc>
imap <left> <esc>
imap <up> <esc>
imap <down> <esc>
