# {{ ansible_managed }}

FROM python:3.10 as pyodbc

ENV DEBIAN_FRONTEND=noninteractive

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y \
    g++ \
    krb5-user \
    msodbcsql18 \
    unixodbc-dev
RUN pip install --user pyodbc
