local opt = vim.opt
opt.autoindent = true -- Default: true
opt.autowrite = true -- Enable auto write, Default: false
opt.clipboard = "unnamedplus" -- Sync with system clipboard, Default: ""
opt.completeopt = "menu,menuone,noselect" -- Default: "menu,preview"
opt.conceallevel = 3 -- Hide * markup for bold and italic, Default: 0
opt.confirm = true -- Confirm to save changes before exiting modified buffer, Default: false
opt.cursorline = true -- Enable highlighting of the current line, Default: false
opt.expandtab = true -- Use spaces instead of tabs, Default: false
opt.formatoptions = "jcroqlnt" -- Controls text formatting, Default: "tcqj"
opt.grepformat = "%f:%l:%c:%m" -- Default: "%f:%l:%m"
opt.grepprg = "rg --vimgrep" -- Default: "grep -n $* /dev/null"
opt.guicursor = "a:block" -- Default: "", allowing default terminal cursor style
opt.hidden = true -- Allow buffer switching without saving, Default: false
opt.hlsearch = false -- Disable highlight search, Default: true
opt.ignorecase = true -- Ignore case when searching, Default: false
opt.inccommand = "nosplit" -- Preview incremental substitute, Default: "none"
opt.incsearch = true -- Default: true
opt.laststatus = 0 -- Hide the status line, Default: 2 (always show status line)
opt.list = true -- Show some invisible characters (tabs, etc.), Default: false
opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
opt.mouse = "a" -- Enable mouse mode in all modes, Default: ""
opt.number = true -- Print line number, Default: false
opt.pumblend = 10 -- Popup blend transparency, Default: 0
opt.pumheight = 10 -- Maximum number of entries in a popup, Default: 0 (unlimited)
opt.relativenumber = true -- Show relative line numbers, Default: false
opt.scrolloff = 4 -- Minimum lines of context above/below cursor, Default: 0
opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize" } -- Default: "blank,buffers,curdir,folds,help,tabpages,winsize"
opt.shiftround = true -- Round indent to a multiple of 'shiftwidth', Default: false
opt.shiftwidth = 2 -- Size of an indent, Default: 8
opt.shortmess:append({ W = true, I = true, c = true }) -- Suppress specific messages, modifies default "filnxtToOF"
opt.showmode = false -- Don’t show mode since we have a statusline, Default: true
opt.sidescrolloff = 8 -- Columns of context when side-scrolling, Default: 0
opt.signcolumn = "yes" -- Always show the signcolumn, Default: "auto"
opt.smartcase = true -- Override 'ignorecase' if search pattern has upper case, Default: false
opt.smartindent = true -- Automatically inserts indents, Default: false
opt.spelllang = { "en" } -- Spell check language, Default: "en"
opt.splitbelow = true -- Split horizontal window below, Default: false
opt.splitright = true -- Split vertical window to the right, Default: false
opt.tabstop = 2 -- Number of spaces tabs count for, Default: 8
opt.termguicolors = true -- Enable true color support, Default: false
opt.timeoutlen = 300 -- Time in milliseconds to wait for a mapped sequence, Default: 1000
opt.undodir = os.getenv("HOME") .. "/.vim/undodir" -- Set undo directory, Default: ""
opt.undofile = true -- Save undo history to file, Default: false
opt.undolevels = 10000 -- Maximum number of undo levels, Default: 1000
opt.updatetime = 200 -- Time of inactivity before a swap file is written, Default: 4000
opt.wildmode = "longest:full,full" -- Command-line completion mode, Default: "full"
opt.winminwidth = 5 -- Minimum window width, Default: 1
opt.wrap = false -- Disable line wrap, Default: true

vim.g.markdown_recommended_style = 0 -- Disable the default recommended markdown settings, Default: Not set
vim.g.mapleader = "," -- Set the map leader key, Default: "\\"
vim.g.maplocalleader = ","
vim.g.loaded_netrw = 1 -- Disable netrw, Default: Not set
vim.g.loaded_netrwPlugin = 1 -- Disable netrwPlugin, Default: Not set
vim.g.loaded_python3_provider = 0 -- Disable python3 provider, Default: Not set
vim.g.have_nerd_front = true

vim.loader.enable() -- Enable module loader, Default: false (This is a new feature in some newer versions of Neovim)
