# {{ ansible_managed }}
FROM debian:buster-slim

ENV MATTERMOST_VERSION 4.2.3

RUN apt update && apt install -y wget

RUN cd /tmp && \
	wget -q https://releases.mattermost.com/desktop/$MATTERMOST_VERSION/mattermost-desktop-$MATTERMOST_VERSION-linux-x64.tar.gz && \
	tar xzvf mattermost-desktop-*.tar.gz && \
	mv mattermost-desktop-$MATTERMOST_VERSION-linux-x64/ /usr/lib/mattermost/

RUN apt install -y \
    gconf-service \
    gconf2 \
    gvfs-bin \
    libappindicator1 \
    libasound2 \
    libatomic1 \
    libc++1 \
    libcap2 \
    libgconf-2-4 \
    libgtk-3-dev \
    libgtk2.0-0 \
    libnotify4 \
    libnss3 \
    libx11-xcb1 \
    libxkbfile1 \
    libxss1 \
    libxtst6 \
    xdg-utils

RUN mkdir /root/Downloads

# cleanup
RUN apt remove --purge -y wget && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/* /var/tmp/*

ENTRYPOINT ["/usr/lib/mattermost/mattermost-desktop"]
