# {{ ansible_managed }}
FROM x11docker/kde-plasma

RUN sudo apt-get update -y && sudo apt-get install -y libsecret-1-0 libgconf-2-4 libnss3 wget libgtk2.0-0 libnotify4 xdg-utils gnome-keyring

RUN wget https://downloads.mongodb.com/compass/mongodb-compass_1.35.0_amd64.deb
RUN sudo dpkg -i mongodb-compass_*.deb

RUN groupadd --gid {{ guid }} {{ user }} \
    && useradd --uid {{ uuid }} --gid {{ user }} --shell /bin/bash --create-home {{ user }}

RUN rm -rf /var/lib/apt/lists/*
RUN apt-get purge --auto-remove -y

USER {{ user }}
CMD ["/usr/bin/mongodb-compass", "--no-sandbox"]
