# {[ ansible_managed }}
FROM alpine:3.6
RUN apk -v --update add \
        python \
        py-pip \
        groff \
        less \
        mailcap \
        && \
    pip install --upgrade awscli && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/*

RUN mkdir -p /root/.aws
ENTRYPOINT ["aws"]
